# Generated by Django 5.0.2 on 2024-02-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIApp', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Project-leader', 'Project-leader'), ('Software-developer', 'Software-developer')], max_length=20),
        ),
    ]
